export enum LeadsActionTypes {
    API_RESPONSE_SUCCESS = "@@leads/API_RESPONSE_SUCCESS",
    API_RESPONSE_ERROR = "@@leads/API_RESPONSE_ERROR",
    GET_LEADS = "@@leads/GET_LEADS",
    GET_LEADS_REGIONAL_MANAGER = "@@leads/GET_LEADS_ASSIGNED_REGIONAL_MANAGER",
    GET_LEADS_TL = "@@leads/GET_LEADS_TL",
    GET_LEADS_ASSIGNED = "@@leads/GET_LEADS_ASSIGNED",
    GET_LEADS_ASSIGNED_BY_COUNSELLOR_TL = "@@leads/GET_LEADS_ASSIGNED_BY_COUNSELLOR_TL",
    GET_LEADS_BY_COUNSELLOR_TL = "@@leads/GET_LEADS_BY_COUNSELLOR_TL",
    GET_LEAD_USER = "@@leads/GET_LEAD_USER",
    ADD_LEADS = "@@leads/ADD_LEADS",
    UPDATE_LEADS = "@@leads/UPDATE_LEADS",
    DELETE_LEADS = "@@leads/DELETE_LEADS",
  }
  