export enum UniversityActionTypes {
  API_RESPONSE_SUCCESS = "@@university/API_RESPONSE_SUCCESS",
  API_RESPONSE_ERROR = "@@university/API_RESPONSE_ERROR",

  GET_UNIVERSITY = "@@university/GET_UNIVERSITY",
  ADD_UNIVERSITY = "@@university/ADD_UNIVERSITY",
  UPDATE_UNIVERSITY = "@@university/UPDATE_UNIVERSITY",
  DELETE_UNIVERSITY = "@@university/DELETE_UNIVERSITY",
}
