export enum FranchiseActionTypes {
  API_RESPONSE_SUCCESS = "@@franchise/API_RESPONSE_SUCCESS",
  API_RESPONSE_ERROR = "@@franchise/API_RESPONSE_ERROR",

  GET_FRANCHISE = "@@franchise/GET_FRANCHISE",
  ADD_FRANCHISE = "@@franchise/ADD_FRANCHISE",
  UPDATE_FRANCHISE = "@@franchise/UPDATE_FRANCHISE",
  DELETE_FRANCHISE = "@@franchise/DELETE_FRANCHISE",
  ADD_FRANCHISE_ADMINUSER = "@@franchise/ADD_FRANCHISE_ADMINUSER",
  UPDATE_FRANCHISE_ADMINUSER = "@@franchise/UPDATE_FRANCHISE_ADMINUSER",
  DELETE_FRANCHISE_ADMINUSER = "@@franchise/DELETE_FRANCHISE_ADMINUSER",
}
