export enum KYCActionTypes {
  API_RESPONSE_SUCCESS = "@@kyc/API_RESPONSE_SUCCESS",
  API_RESPONSE_ERROR = "@@kyc/API_RESPONSE_ERROR",

  GET_PENDING = "@@kyc/GET_PENDING",
  GET_APPLICATION_BY_USER = "@@kyc/GET_APPLICATION_BY_USER",
  GET_REJECTED = "@@kyc/GET_REJECTED",
  GET_APPROVED = "@@kyc/GET_APPROVED",
  ASSIGN_APPLICATION_MEMBER = "@@kyc/ASSIGN_APPLICATION_MEMBER",
  AUTO_ASSIGN_APPLICATION_MEMBER = "@@kyc/AUTO_ASSIGN_APPLICATION_MEMBER",
  OPEN_APPROVAL_MODAL  = "@@kyc/OPEN_APPROVAL_MODAL",
  CLOSE_APPROVAL_MODAL  = "@@kyc/CLOSE_APPROVAL_MODAL",
  TOGGLE_APPROVAL_MODAL = "@@kyc/TOGGLE_APPROVAL_MODAL",
}
