export enum KYCActionTypes {
  API_RESPONSE_SUCCESS = "@@kyc/API_RESPONSE_SUCCESS",
  API_RESPONSE_ERROR = "@@kyc/API_RESPONSE_ERROR",

  GET_PENDING = "@@kyc/GET_PENDING",
  GET_REJECTED = "@@kyc/GET_REJECTED",
  GET_APPROVED = "@@kyc/GET_APPROVED"
}
