export enum KYCActionTypes {
  API_RESPONSE_SUCCESS = "@@kyc/API_RESPONSE_SUCCESS",
  API_RESPONSE_ERROR = "@@kyc/API_RESPONSE_ERROR",

  GET_PENDING = "@@kyc/GET_PENDING",
  GET_PENDING_BY_USER = "@@kyc/GET_PENDING_BY_USER",
  GET_REJECTED = "@@kyc/GET_REJECTED",
  GET_APPROVED = "@@kyc/GET_APPROVED",
  ASSIGN_APPLICATION_MEMBER = "@@kyc/ASSIGN_APPLICATION_MEMBER",
  AUTO_ASSIGN_APPLICATION_MEMBER = "@@kyc/AUTO_ASSIGN_APPLICATION_MEMBER"
}
