export enum CampusActionTypes {
  API_RESPONSE_SUCCESS = "@@campus/API_RESPONSE_SUCCESS",
  API_RESPONSE_ERROR = "@@campus/API_RESPONSE_ERROR",

  GET_CAMPUS = "@@campus/GET_CAMPUS",
  ADD_CAMPUS = "@@campus/ADD_CAMPUS",
  UPDATE_CAMPUS = "@@campus/UPDATE_CAMPUS",
  DELETE_CAMPUS = "@@campus/DELETE_CAMPUS",
  GET_CAMPUS_COURSES = "@@campus/GET_CAMPUS_COURSES",
  CONFIGURE_COURSES = "@@campus/CONFIGURE_COURSES",
  DELETE_CONFIGURE_COURSES = "@@campus/DELETE_CONFIGURE_COURSES",
}
