export enum BranchActionTypes {
    API_RESPONSE_SUCCESS = "@@branches/API_RESPONSE_SUCCESS",
    API_RESPONSE_ERROR = "@@branches/API_RESPONSE_ERROR",
  
    GET_BRANCHES = "@@branches/GET_BRANCHES",
    ADD_BRANCHES = "@@branches/ADD_BRANCHES",
    UPDATE_BRANCHES = "@@branches/UPDATE_BRANCHES",
    DELETE_BRANCHES = "@@branches/DELETE_BRANCHES",
    SET_BRANCH_ID = "@@branches/SET_BRANCH_ID",
    FETCH_BRANCH_ID_FROM_SESSION_STORAGE = "@@branches/FETCH_BRANCH_ID_FROM_SESSION_STORAGE"
  }
  